export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENT = "FETCH_EVENT";

export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const ADD_BOOKED_SEAT = "ADD_BOOKED_SEAT";
export const REMOVE_BOOKED_SEAT = "REMOVE_BOOKED_SEAT";
